### PR TITLE
Add support to multiple --answers arguments

### PR DESCRIPTION
**Pull request by filipenf**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks very much for the patch!

A few super-minor code review/preference things:

    nonexistent = filter(lambda f: not os.path.exists(f), answers)

Can you write this as a list comprehension to make it a little clearer?  I generally try to write list comprehensions all of the time as they are more accessible and easier to tweak/extend.

    nonexistant = [ filename for filename in answers if not os.path.exists(filename) ]

I also changed "inexistent" to "nonexistent" since that is a more commonly used expression, though that might be a regional thing.

In this part...

    raise JCopyException("Answer files: %s does not exist" % ", ".join(inexistent))

Subject/verb argreement here is a tiny bit off here with plural or non-plural handling.  For instance, "files" agrees with there being more than one file, but "does" vs "do" agrees with there being exactly one file.  I would change this to:

    "One or more answer files do not exist: %s" % ...

Finally, all the exceptions are previously lowercased, and now they are a mix of lowercase and uppercase ("Input file", "expecting").  I would go ahead and change the other exception (that this diff did not touch) to start with a capital letter to be consistent.

If you want to tweak these - admittedly very very very small - things, I'll merge it, if not, I'll get to this when I next look at jcp, which shouldn't be too long.

Thanks!

**Comment by filipenf** [comment]
Sure @mpdehaan :+1: 

I'm going make the changes you've pointed out and commit back latter today

**Comment by mpdehaan** [comment]
Thanks very much!  I'll get this tested/merged soon.

**Comment by mpdehaan** [comment]
Sorry for the extremely long delay - I have my GitHub notifications turned off.

I'm unable to work on this one anymore, but would be open to someone maintaining it.  If anyone wants to, I'll update my description and the README to point over there.

**Pull request closed without merging**
